baseURL: "https://open-transport.org/"
title: "Open Transport Community Conference"
defaultContentLanguage: "en"
enableGitInfo: true
enableRobotsTXT: true
buildFuture: true
taxonomies: []

build:
  buildStats:
    enable: true
  cachebusters:
  - source: assets/notwatching/hugo_stats\.json
    target: css
  - source: (postcss|tailwind)\.config\.js
    target: css
module:
  mounts:
  - source: assets
    target: assets
  - source: content
    target: content
  - disableWatch: true
    source: hugo_stats.json
    target: assets/notwatching/hugo_stats.json

markup:
  goldmark:
    extensions:
      typographer: false
      footnote: true
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true

  highlight:
    noClasses: false